#!/usr/bin/env node

/**
 * Test Case Generator MCP Server
 *
 * An MCP server that analyzes application screenshots and generates
 * comprehensive manual test cases.
 */

import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  ListResourcesRequestSchema,
  ReadResourceRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';
import Anthropic from '@anthropic-ai/sdk';
import * as fs from 'fs/promises';
import * as path from 'path';

// Configuration
const WORKSPACE_DIR = process.env.WORKSPACE_DIR || process.cwd();
const MANUAL_TESTS_DIR = path.join(WORKSPACE_DIR, 'manual-tests');
const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;

// Initialize Anthropic client
const anthropic = ANTHROPIC_API_KEY ? new Anthropic({ apiKey: ANTHROPIC_API_KEY }) : null;

// Server instance
const server = new Server(
  {
    name: 'testcase-generator-mcp',
    version: '1.0.0',
  },
  {
    capabilities: {
      tools: {},
      resources: {},
    },
  }
);

/**
 * Analyze screenshot and generate test cases
 */
async function analyzeScreenshot(
  screenshotPath: string,
  appName: string,
  baseUrl: string,
  options?: {
    focusAreas?: string[];
    testTypes?: string[];
    appType?: string;
  }
): Promise<{ summary: string; testCases: string }> {
  if (!anthropic) {
    throw new Error('ANTHROPIC_API_KEY not configured. Set it in environment variables.');
  }

  // Read screenshot
  const imageData = await fs.readFile(screenshotPath);
  const base64Image = imageData.toString('base64');

  // Determine image type
  const ext = path.extname(screenshotPath).toLowerCase();
  const mediaType = ext === '.png' ? 'image/png' : 'image/jpeg';

  // Build analysis prompt
  const focusText = options?.focusAreas?.length
    ? `Focus specifically on: ${options.focusAreas.join(', ')}`
    : '';

  const testTypesText = options?.testTypes?.length
    ? `Generate these test types: ${options.testTypes.join(', ')}`
    : 'Generate all test types: Functional/Positive, Negative, Boundary, Security';

  const appTypeText = options?.appType ? `Application Type: ${options.appType}` : '';

  const prompt = `You are the Test Case Generator Agent. Analyze this screenshot and generate comprehensive manual test cases.

Application Name: ${appName}
Base URL: ${baseUrl}
${appTypeText}

${focusText}
${testTypesText}

Follow these steps:
1. Analyze the screenshot to identify all pages, elements, and user flows
2. Generate a detailed summary of findings
3. Create comprehensive test cases in the following format:

================================================================================
                    ${appName.toUpperCase()} - MANUAL TEST CASES
================================================================================
Application URL: ${baseUrl}
Document Version: 1.0
Created Date: ${new Date().toISOString().split('T')[0]}
Generated By: Test Case Generator MCP Agent v1.0

================================================================================
                              TEST SUMMARY
================================================================================

Total Test Cases: [COUNT]

Module Breakdown:
- [Module]: [count] test cases
  - Positive: [count]
  - Negative: [count]
  - Boundary: [count]
  - Security: [count]

================================================================================
                        MODULE: [MODULE_NAME]
================================================================================

------------------------------------------------------------------------------
TC_[MODULE]_[###]: [Test Case Title]
------------------------------------------------------------------------------
Test Type: [Positive|Negative|Boundary|Security]
Priority: [High|Medium|Low]
Precondition: [Required state]

Test Data:
- field1: value1
- field2: value2

Steps:
1. [Action step]
2. [Action step]

Expected Result:
- [Specific outcome]

------------------------------------------------------------------------------

Generate comprehensive test cases covering:
- Positive tests (minimum 5 per module)
- Negative tests (minimum 5 per module)
- Boundary tests (minimum 2 per module)
- Security tests (minimum 2 per module)

Provide your response in TWO parts:
1. SUMMARY: Brief analysis of what you found
2. TEST_CASES: Complete test case document

Separate them with "===TEST_CASES===" marker.`;

  // Call Claude API
  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 16000,
    messages: [
      {
        role: 'user',
        content: [
          {
            type: 'image',
            source: {
              type: 'base64',
              media_type: mediaType,
              data: base64Image,
            },
          },
          {
            type: 'text',
            text: prompt,
          },
        ],
      },
    ],
  });

  const fullResponse = (response.content[0] as { type: string; text: string }).text;

  // Split summary and test cases
  const parts = fullResponse.split('===TEST_CASES===');
  const summary = parts[0]?.trim() || fullResponse;
  const testCases = parts[1]?.trim() || fullResponse;

  return { summary, testCases };
}

/**
 * Save test cases to file
 */
async function saveTestCases(appName: string, content: string): Promise<string> {
  // Ensure directory exists
  await fs.mkdir(MANUAL_TESTS_DIR, { recursive: true });

  // Generate filename
  const filename = `${appName.replace(/\s+/g, '')}_Manual_Test_Cases.txt`;
  const filePath = path.join(MANUAL_TESTS_DIR, filename);

  // Write file
  await fs.writeFile(filePath, content, 'utf-8');

  return filePath;
}

/**
 * List existing test case files
 */
async function listTestCaseFiles(): Promise<string[]> {
  try {
    await fs.mkdir(MANUAL_TESTS_DIR, { recursive: true });
    const files = await fs.readdir(MANUAL_TESTS_DIR);
    return files.filter(f => f.endsWith('.txt'));
  } catch {
    return [];
  }
}

// Register tools
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: 'analyze_screenshot',
        description:
          'Analyze an application screenshot and generate comprehensive manual test cases. ' +
          'Returns a summary and complete test case document.',
        inputSchema: {
          type: 'object',
          properties: {
            screenshot_path: {
              type: 'string',
              description: 'Path to the screenshot file (PNG or JPG)',
            },
            app_name: {
              type: 'string',
              description: 'Name of the application',
            },
            base_url: {
              type: 'string',
              description: 'Base URL of the application',
            },
            app_type: {
              type: 'string',
              description: 'Type of application (e.g., E-commerce, SaaS, Web App)',
            },
            focus_areas: {
              type: 'array',
              items: { type: 'string' },
              description: 'Specific areas to focus on (optional)',
            },
            test_types: {
              type: 'array',
              items: { type: 'string' },
              description: 'Test types to generate: Positive, Negative, Boundary, Security (optional)',
            },
            auto_save: {
              type: 'boolean',
              description: 'Automatically save test cases to manual-tests/ directory',
              default: true,
            },
          },
          required: ['screenshot_path', 'app_name', 'base_url'],
        },
      },
      {
        name: 'save_test_cases',
        description: 'Save test cases content to a file in manual-tests/ directory',
        inputSchema: {
          type: 'object',
          properties: {
            app_name: {
              type: 'string',
              description: 'Name of the application (used for filename)',
            },
            content: {
              type: 'string',
              description: 'Test cases content to save',
            },
          },
          required: ['app_name', 'content'],
        },
      },
      {
        name: 'list_test_cases',
        description: 'List all test case files in manual-tests/ directory',
        inputSchema: {
          type: 'object',
          properties: {},
        },
      },
    ],
  };
});

// Handle tool calls
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    switch (name) {
      case 'analyze_screenshot': {
        const {
          screenshot_path,
          app_name,
          base_url,
          app_type,
          focus_areas,
          test_types,
          auto_save = true,
        } = args as {
          screenshot_path: string;
          app_name: string;
          base_url: string;
          app_type?: string;
          focus_areas?: string[];
          test_types?: string[];
          auto_save?: boolean;
        };

        const result = await analyzeScreenshot(screenshot_path, app_name, base_url, {
          appType: app_type,
          focusAreas: focus_areas,
          testTypes: test_types,
        });

        let savedPath: string | undefined;
        if (auto_save) {
          savedPath = await saveTestCases(app_name, result.testCases);
        }

        return {
          content: [
            {
              type: 'text',
              text: `# Test Case Generation Complete\n\n## Summary\n\n${result.summary}\n\n${
                savedPath ? `\n✅ Test cases saved to: ${savedPath}\n` : ''
              }\n## Generated Test Cases\n\n${result.testCases}`,
            },
          ],
        };
      }

      case 'save_test_cases': {
        const { app_name, content } = args as { app_name: string; content: string };
        const filePath = await saveTestCases(app_name, content);

        return {
          content: [
            {
              type: 'text',
              text: `✅ Test cases saved successfully to: ${filePath}`,
            },
          ],
        };
      }

      case 'list_test_cases': {
        const files = await listTestCaseFiles();

        return {
          content: [
            {
              type: 'text',
              text:
                files.length > 0
                  ? `Test case files in manual-tests/:\n${files.map(f => `- ${f}`).join('\n')}`
                  : 'No test case files found in manual-tests/ directory.',
            },
          ],
        };
      }

      default:
        throw new Error(`Unknown tool: ${name}`);
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    return {
      content: [
        {
          type: 'text',
          text: `Error: ${errorMessage}`,
        },
      ],
      isError: true,
    };
  }
});

// Register resources
server.setRequestHandler(ListResourcesRequestSchema, async () => {
  const files = await listTestCaseFiles();

  return {
    resources: files.map(filename => ({
      uri: `testcase:///${filename}`,
      name: filename,
      description: `Manual test cases for ${filename.replace('_Manual_Test_Cases.txt', '')}`,
      mimeType: 'text/plain',
    })),
  };
});

// Read resource
server.setRequestHandler(ReadResourceRequestSchema, async (request) => {
  const uri = request.params.uri;
  const filename = uri.replace('testcase:///', '');
  const filePath = path.join(MANUAL_TESTS_DIR, filename);

  try {
    const content = await fs.readFile(filePath, 'utf-8');
    return {
      contents: [
        {
          uri,
          mimeType: 'text/plain',
          text: content,
        },
      ],
    };
  } catch (error) {
    throw new Error(`Failed to read test case file: ${filename}`);
  }
});

// Start server
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error('Test Case Generator MCP server running on stdio');
}

main().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
